### ISSUE TITLE
Add event logging to DB?

### ISSUE THREAD

**Issue by ochompsky** [aileftech/snap-admin#48]
It looks like it logs to a local h2 db, which is not ideal for docker containers without persistant storage.  I wonder the feasibility of logging to an actual db server?   

I'm going to play around with SnapAdminAutoConfiguration as that seems to be the place to do these changes.

**Comment by ochompsky** [comment]
so i've overwritten the beans and can get it to create the db structure in my remote db but now am having spring issues.  

as an aside the word 'sql' is reserved in mysql so it's not ideal for a column name

**Comment by ochompsky** [comment]
i've forked a version of this here https://github.com/ochompsky/snap-admin/tree/main

in that version, it will allow for a remotely specified db connection.  in your properties you will need something like:
```
internal:
  datasource:
    driver-class-name: "org.postgresql.Driver"
    url: "jdbc:postgresql://server:5432/postgres"
    username: "user"
    password: "pass"
    hibernate-dialect: "org.hibernate.dialect.PostgreSQLDialect"
    hbm2ddl-auto: update
```

note that i've only tested it with postgres.  i know for a fact it will not work with mysql because the column sql needs to be renamed.
